# devc version
version: v1.0.0

# cache directory used by devc
cache-dir: ".cache/devc"
cache-expiry-hrs: 720   # 30 days

proot:
  url: https://proot.gitlab.io/proot/bin/proot
  version: v5.3.1

buildah:
  path: buildah