name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "ReleaseBuild"
    runs-on: "ubuntu-latest"
    timeout-minutes: ${{ (matrix.language == 'swift' && 120) || 360 }}
    strategy:
      fail-fast: false
      matrix:
        language: [ 'go' ]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    
    - name: "Build"
      run: |
        bash scripts/build-all-arch.sh
      working-directory: "."
      if: steps.build.outputs.exit_code == 0

    - name: "Test"
      # only testing amd64 and 386 builds, as the github machine do not support others
      run: | 
        set -e
        sudo apt-get install -y buildah
        for exe in devc-v*amd64 devc-v*386 ; do echo -e "\nTesting $exe"; if ! ./$exe --version ; then echo "Error executing : $exe" ; exit 1; fi; done ;
      working-directory: "."
      if: steps.build.outputs.exit_code == 0

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          LICENSE
          devc-v*
      if: steps.build.outputs.exit_code == 0